version: '2'
services:
  match:
    image: truepic/match:0.0.5
    ports:
    - 8888:8888
    environment:
    - ELASTICSEARCH_URL=elasticsearch:9200
    - PORT=8888
    links:
    - elasticsearch
  elasticsearch:
    image: elasticsearch:6.4.2
    ports:
    - 9200:9200
